apiVersion: v1
kind: Service
metadata:
  name: vcluster-service
  namespace: operations
spec:
  selector:
    app: vcluster 
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
  type: LoadBalancer