repositories:
  - name: harbor
    url: https://helm.goharbor.io

releases:
  - chart: harbor/harbor
    cleanupOnFail: true
    devel: false
    name: harbor
    namespace: registry
    skipDeps: false
    version: 1.12.1
    values:
      - ./values/harbor.yaml
  - chart: ./dev-package
    name: dev-packages
    cleanupOnFail: true
    devel: false
    namespace: dev
    skipDeps: false
    version: 0.1.0
    values:
      - ./values/dev-packages.yaml
