apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert-registry
{{- with (index .Values.ingress.tls 0)}}
spec:
  isCA: true
  secretName: {{ .secretName }}
  issuerRef:
    name: full-cloudflare-issuer
    kind: ClusterIssuer
  duration: 2160h # 90d
  renewBefore: 720h #15d
  commonName: {{ index .hosts 0 }}
  dnsNames:
    {{- .hosts | toYaml | nindent 4 }}
{{- end }}