# Default values for apigateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.athmos-cloud.com/athmos/api-athmos
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""
command: ["pnpm"]
args: ["run", "start:prod"]

env:
  secrets:
  - name: "RMQ_PASSWORD"
    secretName: "rabbitmq-auth"
    secretKey: "rabbitmq-password"
  - name: "DATABASE_PASSWORD"
    secretName: "neo4j-gateway-auth"
    secretKey: "password"
  - name: "DEFAULT_ADMIN_PASSWORD"
    secretName: "admin-secret"
    secretKey: "password"
  - name: "SECRET"
    secretName: "secret-api-secret"
    secretKey: "secret"
  raw:
  - name: "ATHMOS_URL"
    value: "https://api.athmos-cloud.com"
  - name: "DATABASE_URL"
    value: "neo4j://neo4j-gateway:7687"
  - name: "DATABASE_USER"
    value: "neo4j"
  - name: "RMQ_HOST"
    value: "rabbitmq.common.svc.cluster.local"
  - name: "RMQ_PORT"
    value: "5672"
  - name: "RMQ_USER"
    value: "athmos"
  - name: "RMQ_WRITE_QUEUE"
    value: "to-gateway-api"
  - name: "RMQ_READ_QUEUE"
    value: "to-gateway-api"
  - name: "RESSOURCES_MANAGER_URL"
    value: "http://apigateway.infra.svc.cluster.local"
  


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: api.athmos-cloud.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: api-secret-tls
     hosts:
       - api.athmos-cloud.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
