apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: full-cloudflare-issuer
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.issuer }}
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .email }}
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    -  dns01:
        cloudflare:
          email: {{ .email }}
          apiKeySecretRef:
            name: {{ .apiToken.secretName }}
            key: {{ .apiToken.secretKey }}
  {{- end }}
