apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert-registry
  namespace: {{ .Values.registry.namespace }}
spec:
  isCA: true
  secretName: {{ .Values.registry.certSecretName }}
  issuerRef:
    name: full-cloudflare-issuer
    kind: ClusterIssuer
  duration: 2160h # 90d
  renewBefore: 720h #15d
  commonName: {{ .Values.host }}
  dnsNames:
    - "{{ .Values.host }}"
    - "*.{{ .Values.host }}"