repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: neo4j-helm-charts
    url: https://neo4j.github.io/helm-charts/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - chart: traefik/traefik
    cleanupOnFail: true
    devel: false
    name: traefik
    namespace: traefik
    createNamespace: true
    skipDeps: false
    version: 23.0.1
    values:
      - ./values/traefik.yaml
  
  - chart: cert-manager/cert-manager
    cleanupOnFail: true
    devel: false
    name: cert-manager
    namespace: cert-manager
    createNamespace: true
    skipDeps: false
    version: 1.12.0
    values:
      - installCRDs: true
  
  - chart: ./common
    name: common
    cleanupOnFail: true
    devel: false
    namespace: common
    createNamespace: true
    skipDeps: false
    version: 0.1.0
    values:
      - ./values/common.yaml

  #https://artifacthub.io/packages/helm/neo4j-helm-charts/neo4j-standalone
  - chart: neo4j-helm-charts/neo4j
    cleanupOnFail: true
    devel: false
    name: neo4j-gateway
    namespace: gateway
    createNamespace: true
    skipDeps: false
    version: 5.9.0
    values:
      - ./values/neo4j.yaml

  #https://artifacthub.io/packages/helm/bitnami/mongodb
  - chart: bitnami/mongodb
    cleanupOnFail: true
    devel: false
    name: mongodb
    namespace: infra
    createNamespace: true
    skipDeps: false
    version: 13.15.3
    values:
      - ./values/mongodb.yaml
  
  #https://artifacthub.io/packages/helm/bitnami/rabbitmq
  - chart: bitnami/rabbitmq
    name: rabbitmq
    namespace: common
    createNamespace: true
    version: 12.0.3
    cleanupOnFail: true
    values:
      - ./values/rabbitmq.yaml
  
  - chart: ./app
    name: app-frontend
    namespace: frontend
    createNamespace: true
    version: 0.1.0
    cleanupOnFail: true
  
  - chart: ./api-gateway
    name: api-gateway
    namespace: gateway
    createNamespace: true
    version: 0.1.0
    cleanupOnFail: true

  - chart: ./infra-worker
    name: infra-worker
    namespace: infra
    createNamespace: true
    version: 0.1.0
    cleanupOnFail: true

  # - chart: ./infra-watcher
  #   name: infra-watcher
  #   namespace: infra
  #   createNamespace: true
  #   version: 0.1.0
  #   cleanupOnFail: true