replicaCount: 1

image:
  repository: registry.athmos-cloud.com/athmos/infra-watcher-athmos
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
- name: regcred
nameOverride: ""
fullnameOverride: ""

command: ["/app"]
config:
  name: "infra-watcher-config"
  envVariableName: "CONFIG_FILE_LOCATION"
  folder: "/etc/athmos"
  filename: "config.yaml"

kubeConfig:
  name: "operations-kubeconfig"
  envVariableName: "KUBECONFIG_PATH"
  folder: "/root/.kube"
  filename: "config"

env:
  secrets:
  - name: "RABBITMQ_PASSWORD"
    secretName: "rabbitmq-auth"
    secretKey: "rabbitmq-password"

rabbitmq:
  address: "rabbitmq.common.svc.cluster.local"
  port: 5672
  username: "athmos"
  outcoming: "to-gateway-api"
  incoming: "to-infra-watcher"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 60m
    memory: 100Mi
  requests:
    cpu: 60m
    memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
